# Generated by Django 3.2.2 on 2021-05-18 17:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('qr_position', models.CharField(choices=[('TOP_LEFT', 'Top left'), ('TOP_RIGHT', 'Top right'), ('BOTTOM_LEFT', 'Bottom left'), ('BOTTOM_RIGHT', 'Bottom right')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
