# Generated by Django 3.2.2 on 2021-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        ('album', '0002_albumitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='interviews',
            field=models.ManyToManyField(to='interview.Interview'),
        ),
        migrations.DeleteModel(
            name='AlbumItem',
        ),
    ]
