# Generated by Django 3.2.2 on 2021-06-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20210518_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created']},
        ),
    ]
