# Generated by Django 3.2.2 on 2021-06-24 05:00

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interview_name'),
        ('album', '0005_alter_album_managers'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='album',
            name='interviews',
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, to='interview.Interview'),
        ),
    ]
