# Generated by Django 3.2.2 on 2021-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_mode', models.CharField(choices=[('ORIGINAL', 'Original'), ('COLOR_BLIND', 'Color blind')], default='ORIGINAL', max_length=255)),
                ('font_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', max_length=255)),
                ('elements_per_page', models.IntegerField(choices=[(4, 'Few'), (8, 'Intermediate'), (16, 'Many')], default=4)),
            ],
        ),
    ]
