# Generated by Django 3.2.2 on 2021-07-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210703_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='elements_per_page',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='font_size',
        ),
        migrations.AlterField(
            model_name='settings',
            name='color_mode',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('HIGH_CONTRAST', 'High contrast')], default='ORIGINAL', max_length=255),
        ),
    ]
