# Generated by Django 3.2.2 on 2021-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
