# Generated by Django 3.2.2 on 2021-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_youtubevideo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
