# Generated by Django 3.2.2 on 2021-07-15 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210714_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='youtube_video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.youtubevideo'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together=set(),
        ),
    ]
